/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    copy: typeof import('./src/components/ECharts/EChartsBar copy.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    EChartsAll: typeof import('./src/components/EChartsAll.vue')['default']
    EChartsBar: typeof import('./src/components/ECharts/EChartsBar.vue')['default']
    EChartsLine: typeof import('./src/components/ECharts/EChartsLine.vue')['default']
    EChartsPie: typeof import('./src/components/ECharts/EChartsPie.vue')['default']
    EchartsScatter: typeof import('./src/components/ECharts/EchartsScatter.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    SocketIO: typeof import('./src/components/SocketIO.vue')['default']
  }
}
